### ISSUE TITLE
workflow怎么安装？

### ISSUE THREAD

**Issue by gilles6** [tianhao/alfred-wubi-workflow#1]
”安装本 workflow“
怎么安装？

**Comment by tianhao** [comment]
双击 wubi.alfredworkflow 文件

**Comment by gilles6** [comment]
![image](https://user-images.githubusercontent.com/612946/36437518-2cb2a8b2-16a2-11e8-9bcd-fe2d9bbfba6f.png)

**Comment by tianhao** [comment]
这是alfred的 workflow，首先需要安装alfred，而且要付费的
