### ISSUE TITLE
终于找到一个五笔查询的

### ISSUE THREAD

**Issue by iHTCboy** [tianhao/alfred-wubi-workflow#2]
感谢！！

但是为什么要缓存？我就是有时不知道这个字怎么打，想查一下，根本不打算保存的。还有在document创建目录。。。。希望增加一个开关控制？

**Comment by tianhao** [comment]
图片是要放在本地才能展示出来，所以一定会用一个目录缓存；
输入"wb"不输入汉字会展示最近查过的字，复习时就不用再查网络了；
想删除历史记录删除缓存文件夹就可以了。

**Comment by iHTCboy** [comment]
尽然不是文字。。。。好吧，可以看看有没有其它免费的查询接口，用用

**Comment by tianhao** [comment]
拆字示意图+字根字符

**Comment by iHTCboy** [comment]
![jietu20180712-175935](https://user-images.githubusercontent.com/11418363/42626615-5e7dec24-85fd-11e8-9ac2-817fa012b6d8.jpg)

像这个一样，我的意思是，我只是想查一下这个字应该怎样打啊（有时候用拼音打字，但是不会五笔怎么输入），但是现在在 文档自动生成这个：

![jietu20180712-180059](https://user-images.githubusercontent.com/11418363/42626700-8d816a0a-85fd-11e8-8333-b2783ef46f4d.jpg)

我意思是不想要缓存。

**Comment by tianhao** [comment]
我觉得缓存没关系,如果你不想缓存,可以自已改脚本

**Comment by iHTCboy** [comment]
@tianhao 好的！有空我研究研究，谢谢分享！
